chef/automate-liveness-agent

lib/automate_liveness_agent/liveness_update_sender.rb
spec/automate_liveness_agent/liveness_update_sender_spec.rb

Fix data collector message to use 'event_type'

---

lib/automate_liveness_agent/main.rb
spec/automate_liveness_agent/main_spec.rb

Implement privilege drop

---

design_goals.md

Add brief explanation of technical choices

---

.gitignore
.kitchen.yml
Berksfile
Berksfile.lock
automate-liveness-agent.gemspec
lib/recipe.rb
tasks/compile.rb
test/cookbooks/liveness-agent-test/.gitignore
test/cookbooks/liveness-agent-test/Berksfile
test/cookbooks/liveness-agent-test/attributes/default.rb
test/cookbooks/liveness-agent-test/files/default/automate/Gemfile
test/cookbooks/liveness-agent-test/files/default/automate/app.rb
test/cookbooks/liveness-agent-test/files/default/automate/config.ru
test/cookbooks/liveness-agent-test/metadata.rb
test/cookbooks/liveness-agent-test/recipes/compiled-recipe.rb
test/cookbooks/liveness-agent-test/recipes/default.rb
test/cookbooks/liveness-agent-test/recipes/faux-automate.rb
test/cookbooks/liveness-agent-test/recipes/test-client.rb
test/integration/default/agent_spec.rb

* Add rake task to compile liveness agent into a self installing recipe
* Add test harness for validating recipe on target platforms
* Add initial Ubuntu platform support

[CLOUD-332] Compile liveness agent into recipe

---

README.md
RELEASE_PLAN.md

Still a lot to be filled out...

Initial release plan

---

lib/automate_liveness_agent/config.rb
lib/automate_liveness_agent/main.rb
spec/automate_liveness_agent/config_spec.rb
spec/automate_liveness_agent/main_spec.rb
spec/fixtures/config/valid_config.json

Lets us run on windows via scheduled task instead of as a service.

Create scheduled task mode that doesn't loop

---

lib/recipe.rb

Init script needed some adjustments for backgrounding;
Logging needed to be handled by app and also ensure our dir has the
correct owner

Update init and logging

---

.kitchen.yml
lib/recipe.rb

Add Amazon Linux support to recipe and test harness

[CLOUD-336] Add Amazon Linux support

---

RELEASE_PLAN.md

Looking for input on a few of these right now, will add comments inline.

Add more tasks to release plan

---

.kitchen.yml
lib/recipe.rb

WIP
This installs a scheduled task that runs the agent standalone, and hopefully sets up all the configuration files properly. I got the agent starting up, but haven't tested past that because of harness issues.
Known missing pieces
[] porting the test harness to windows
[] verifying the agent actually starts and runs properly
[] Fixing windows popup when task is run
[] Making sure paths seem reasonable for windows.
[] Making scheduled task setup idempotent

Cloud 337/windows

---

lib/recipe.rb

We need to copy the ssl modes and trusted certs from the chef client config file or
ssl will fail when we don't have a signed cert.

Fix SSL issues mode

---

.kitchen.yml
lib/recipe.rb

2012 works, 2016 doesn't
Signed-off-by: Mark Anderson <mark@chef.io>

Add windows 2012 & 2016 to test matrix

---

.kitchen.yml
lib/recipe.rb

[CLOUD-350] Add Solaris support to the liveness agent recipe

[CLOUD-350] Add Solaris support to the liveness agent recipe

---

.kitchen.yml
lib/recipe.rb

Rework the default paths to match the standard windows paths for chef client.

Cloud 372/windows paths

---

.gitignore
LICENSE
automate-liveness-agent.gemspec

We decided to open source this but forgot the licensing boilerplate.

Add license files

---

Rakefile
lib/automate_liveness_agent/main.rb
lib/automate_liveness_agent/vendor/mixlib-authentication/lib/mixlib/authentication.rb
lib/automate_liveness_agent/vendor/mixlib-authentication/lib/mixlib/authentication/http_authentication_request.rb
lib/automate_liveness_agent/vendor/mixlib-authentication/lib/mixlib/authentication/signedheaderauth.rb
lib/automate_liveness_agent/vendor/mixlib-authentication/lib/mixlib/authentication/version.rb
lib/automate_liveness_agent/version.rb
lib/compile_to_file/source_file.rb
lib/recipe.rb
spec/automate_liveness_agent/api_client_spec.rb
spec/automate_liveness_agent/config_spec.rb
spec/automate_liveness_agent/main_spec.rb
tasks/compile.rb
tasks/lint.rb
test/cookbooks/liveness-agent-test/Berksfile
test/cookbooks/liveness-agent-test/attributes/default.rb
test/cookbooks/liveness-agent-test/metadata.rb
test/cookbooks/liveness-agent-test/recipes/faux-automate.rb
test/cookbooks/liveness-agent-test/recipes/test-client.rb

Signed-off-by: Jaymala Sinha <jsinha@chef.io>

Add support for SLES 15 configure service

---

lib/recipe.rb

#! needs to be the the first line without spaces

Remove extra spaces

---

.cookstyle.yml
lib/automate_liveness_agent/version.rb
lib/recipe.rb

Signed-off-by: Steven Danna <steve@chef.io>

Bump version to 0.7.4

---

lib/automate_liveness_agent/version.rb
lib/recipe.rb

Don't assume chef-sugar

---

README.md

Causes github to render it wrong
Signed-off-by: Tim Smith <tsmith@chef.io>

Add missing comma in the readme JSON
